# Generated by Django 4.2.29 on 2026-03-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PETICION', 'Petición'), ('QUEJA', 'Queja'), ('RECLAMO', 'Reclamo'), ('SUGERENCIA', 'Sugerencia'), ('FELICITACION', 'Felicitación')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RESPONDIDA', 'Respondida'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('nombre_anonimo', models.CharField(blank=True, help_text='Si no está registrado', max_length=100)),
                ('correo_contacto', models.EmailField(blank=True, help_text='Para enviar respuesta', max_length=254)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('radicado', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'pqrs',
                'ordering': ['-created_at'],
            },
        ),
    ]
