# Generated by Django 4.2.29 on 2026-03-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqrs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='respondida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
