# Generated by Django 4.2.29 on 2026-03-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioficha',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='core.programa'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='core.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioficha',
            unique_together={('usuario', 'ficha')},
        ),
    ]
