# Generated by Django 4.2.29 on 2026-03-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Elemento',
                'verbose_name_plural': 'Categorías de Elementos',
                'db_table': 'categoria_elementos',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_elemento', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_elemento', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja'), ('AGOTADO', 'Sin Stock')], default='DISPONIBLE', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stock_total', models.PositiveIntegerField(default=1, help_text='Cantidad total de este elemento')),
                ('stock_disponible', models.PositiveIntegerField(default=1, help_text='Cantidad disponible para préstamo')),
                ('stock_minimo', models.PositiveIntegerField(default=1, help_text='Alerta cuando el stock baja de este valor')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Sala Bienestar, Armario 2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'elementos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida / Préstamo'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste de inventario'), ('BAJA', 'Baja definitiva')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_antes', models.PositiveIntegerField()),
                ('stock_despues', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservaElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Fecha prevista de devolución', null=True)),
                ('descripcion_reserva', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva de Elemento',
                'verbose_name_plural': 'Reservas de Elementos',
                'db_table': 'reservaelementos',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('motivo_reserva', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('duracion', models.PositiveIntegerField(default=60, help_text='Duración en minutos')),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.espacio')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ficha')),
            ],
            options={
                'verbose_name': 'Reserva de Espacio',
                'verbose_name_plural': 'Reservas de Espacios',
                'db_table': 'reservaespacios',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
