# Generated by Django 4.2.29 on 2026-03-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('asesorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorias', to='core.ficha'),
        ),
    ]
